server:
  port: 8101
spring:
    datasource:
        name: test
        url: jdbc:mysql://39.106.206.72:3306/mcv
        username: root
        password: rootpass
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        host: localhost
        port: 6379
        database: 2
        pool:
          max-idle: 100
          min-idle: 1
          max-active: 1000
          max-wait: -1

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ysc.device.service.domain.entities  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

config:
    cos:
        secretId: AKIDgDXcR0vbjeQbcQMNYVEj15vWv62lqbhZ
        secretKey: nNjrlQs77tVBhYDev1sXyA8sOgkaFgtr
        regionName: ap-shanghai
